# Generated by Django 3.2.2 on 2022-06-10 21:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='media/actores')),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('biografia', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='media/directores')),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', django_countries.fields.CountryField(max_length=2)),
                ('biografia', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.CharField(max_length=300)),
                ('imagen', models.ImageField(null=True, upload_to='media/peliculas')),
                ('fecha_lanzamiento', models.DateField()),
                ('puntaje', models.IntegerField(default=1)),
                ('actores', models.ManyToManyField(to='catalogo.Actor')),
                ('categorias', models.ManyToManyField(to='catalogo.Categoria')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.director')),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.CharField(max_length=300)),
                ('puntaje', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('habilitado', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to='catalogo.pelicula')),
            ],
        ),
    ]
