# Generated by Django 3.2.2 on 2022-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='biografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
