# Generated by Django 3.2.2 on 2022-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20220727_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='actores',
            field=models.ManyToManyField(related_name='peliculas', to='catalogo.Actor'),
        ),
    ]
